//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuppyGo.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PuppyGo.Resources.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string tabs_browse {
            get {
                return ResourceManager.GetString("tabs_browse", resourceCulture);
            }
        }
        
        internal static string tabs_about {
            get {
                return ResourceManager.GetString("tabs_about", resourceCulture);
            }
        }
        
        internal static string itemspage_title {
            get {
                return ResourceManager.GetString("itemspage_title", resourceCulture);
            }
        }
        
        internal static string itemdetailspage_name_header {
            get {
                return ResourceManager.GetString("itemdetailspage_name_header", resourceCulture);
            }
        }
        
        internal static string itemdetailspage_description_header {
            get {
                return ResourceManager.GetString("itemdetailspage_description_header", resourceCulture);
            }
        }
        
        internal static string itemdetailspage_adoptbutton_text {
            get {
                return ResourceManager.GetString("itemdetailspage_adoptbutton_text", resourceCulture);
            }
        }
        
        internal static string aboutpage_title {
            get {
                return ResourceManager.GetString("aboutpage_title", resourceCulture);
            }
        }
        
        internal static string aboutpage_text {
            get {
                return ResourceManager.GetString("aboutpage_text", resourceCulture);
            }
        }
    }
}
